###
GET http://localhost:3000/setting


###
GET http://localhost:3000/setting/theme/all

###
GET http://localhost:3000/article/read/all

###
GET http://localhost:3000/article/read/8ad5759d-e6a5-4d73-a5fa-6769ad3105ad

###
POST http://localhost:3000/setting
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJiOWVkNmQ4OS1jODA4LTQxODAtOTAxOS0yODVkMzQyMTNlOWQiLCJpYXQiOjE2ODkyNzEyNjMsImV4cCI6MTY4OTI3NDg2M30.MG8SuNmozG_fbKgNgxih-NqrGZ261jiwmKTIOXrCjFo
Content-Type: application/json

{
  "title": "Blog",
  "subtitle": "",
  "carousel_amount": 3,
  "carousel_time": 3000,
  "theme_id": 2,
  "articles_per_page": 2
}